### ISSUE TITLE
pull_request_review event

### ISSUE THREAD

**Issue by thinca** [softprops/afterparty#29]
I would like to receive [`pull_request_review`](https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent) event, but it seems not to be supported.
Any plan to support this?

By the way, the following events do not seem to be supported (I compared [event list in GitHub](https://developer.github.com/webhooks/#events) and [afterparty's document](http://lessis.me/afterparty/afterparty/enum.Event.html)).
For now, I am interested only in `pull_request_review` event.

- [`installation`](https://developer.github.com/v3/activity/events/types/#installationevent)
- [`installation_repositories`](https://developer.github.com/v3/activity/events/types/#installationrepositoriesevent)
- [`label`](https://developer.github.com/v3/activity/events/types/#labelevent)
- [`marketplace_purchase`](marketplace_purchase)
- [`milestone`](https://developer.github.com/v3/activity/events/types/#milestoneevent)
- [`organization`](https://developer.github.com/v3/activity/events/types/#organizationevent)
- [`org_block`](https://developer.github.com/v3/activity/events/types/#orgblockevent)
- [`project_card`](https://developer.github.com/v3/activity/events/types/#projectcardevent)
- [`project_column`](https://developer.github.com/v3/activity/events/types/#projectcolumnevent)
- [`project`](https://developer.github.com/v3/activity/events/types/#projectevent)
- [`pull_request_review`](https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent)
- [`team`](https://developer.github.com/v3/activity/events/types/#teamevent)

**Comment by softprops** [comment]
Most of these are new relative to the last time the list of events were generated. I'll look into syncing these up. I'm on vacation now but I can look when I get back

**Comment by rbvea** [comment]
Would appreciate a `project_card` event :pray:

**Comment by 19h** [comment]
@rbvea @thinca I updated the list of events for use at our company, maybe you can make use of it: https://github.com/psychonautwiki/afterparty-ng

**Comment by softprops** [comment]
@KenanSulayman would you have any interest in taking over this crate? Its been a while since I've had time to move this project forward. I'd be happy to transfer it over

**Comment by softprops** [comment]
I could also just add a link to yours in this repos  readme

**Comment by 19h** [comment]
@softprops I would prefer just being added as a contributor to this repo and the crate, there's no need to create a new one :-) 🐝

**Comment by thinca** [comment]
I opened this issue for personal purposes, but now I do not need it.
If time comes when I need this, I will try afterparty-ng.
Thanks all!
